WebThingsIO/addon-list

- list.json
- test.json
Since master is broken without this, r=me
> Sync with add-dimmer branch of gateway.

- list.json
- test.json
Also, update example and GPIO releases.
> Add Z-Wave and Zigbee add-ons.

- list.json
Update both to properly use manifest.name
> Update virtual-things and philips-hue adapters

- check-list.py
It now verifies that the name, version and api versions
match between list.json and the packages in question.
> Enhance check-list.py

- list.json
> Add BroadLink adapter.

- list.json
> Add ESP-adapter.

- README.md
- check-list.py
- list.json
- test.json
If you turn off whitespace in the diff, it's much smaller.
> Add support for architecture-specific packages.

- list.json
- test-server.py
- test.json
Also, add a test server for local testing.
> Update most add-ons to support API level 2.

- list.json
Reverts mozilla-iot/addon-list#34
> Revert "Bump Zigbee to 0.3.3."

- list.json
> Add HomeKit adapter.

- list.json
> Add LIFX adapter.

- check-list.py
- list.json
- test-server.py
- test.json
* Update gpio
* Update serial
* Update zigbee
* Update zwave
* Add thing-url
* Remove ESP
Fixes #45
> Update packages with native dependencies.

- list.json
The adapter currently supports discovering devices, changing volume, play state, shuffle and repeat all (including listening for changes to those states).
> Add basic sonos adapter

- list.json
This adds support for the Pimoroni Blinkt! on Raspberry Pi
> Added blinkt-adapter

- list.json
Would you please consider publishing my adapter to control X10 devices through the CM11 serial interface?  It has been controlling dimmable lights in my house for a few weeks now.  Any comments, suggestions would be welcome.  Thanks, alan
> Add X10 CM11 Adapter.

- check-list.py
There isn't any point in reporting missing author in packages that aren't likely to ever be updated
> Don't bother checking author on legacy packages

- list.json
> Bump broadlink adapter 0.1.4

- list.json
This fixes some issues with properties not updating and devices disappearing.
> Update Netatmo Weather Station adapter to version 0.1.2

- list.json
Only contains changes from @mrstegeman
> Update Blinkt! Adapter to version 0.0.4

- list.json
> Add Wemo adapter.

- list.json
> Add Yeelight adapter.

- list.json
More adapters \o/. This one even has events!
> Add chromecast adapter

- check-list.py
This list of adapters is getting quite long. This commit
does 2 things:
1 - gives some progress
2 - allows a single adapter to be checked.
> Allow a single adapter to be checked.

- list.json
and a bug fix for grouping sonos players and probably other changes I've forgot about.
> Update the adapters of @freaktechnik for versions with readOnly support

- check-list.py
- list.json
> Add DateTime adapter.

- list.json
> Add zigbee-conbee-adapter.

- list.json
Relate-to: https://github.com/rzr/mastodon-lite/releases/tag/v0.0.8
Change-Id: I72911b1b762b9330655b77ec29cffd0f3f71d997
> Add activitypub-adapter.

- list.json
> Voice-Addon 0.3

- README.md
- check-list.py
- list.json
References mozilla-iot/gateway#1274
> Include licenses in list.

- list.json
This commit was created using the update.py script from #173
> Bumped zigbee adapter to 0.7.0

- list.json
> Add ONVIF adapter.

- list.json
Primarily using new schema things and making the license file prettier.
> Bump in prepration of gateway 0.7 for @freaktechnik's adapters

- list.json
> bump to 0.0.8

- list.json
Updated DateTime adapter to use gateway >= 0.7
> New version of DateTime adapter

- check-list.py
Fixes mozilla-iot/gateway#1289
> Loosen checks on author to handle email addresses.

- list.json
Fix mistake in ID generation
Change-Id: Ieb24c7a822398ead28e6e1c2f100baaa5dc75d5d
> Update activitypub-adapter to 0.0.10

- list.json
Fixed a small bug with recovering from connection issues.
> Bump logitech harmony adapter

- list.json
Adds network timeout handling (yay, UDP)
> Update maxsmart2 adapter

- list.json
Adds pairing and discovery as well as some more meta data in the thing spec.
> Upgrade maxSMART adapter

- list.json
> Add MySensors adapter.

- list.json
I've built a little addon which allows the user to send slack messages.
The details about how to use it are in the readme.
> Add slack addon

- list.json
Fixes sonos API incompatibilities.
> Bump sonos adapter

- list.json
- Support expanded to serial, ethernet and MQTT.
- Small improvements
- Done more tests with more devices, which shows everything works quite well.
> MySensors to version 0.0.2

- list.json
Resolves https://github.com/mozilla-iot/gateway/issues/1392
> Add enocean addon

- list.json
Resolves https://github.com/mozilla-iot/gateway/issues/636
I think we also need a cross compile build here.
> Add mi flora adapter

- list.json
> Add network-presence-detection-adapter.

- list.json
Resolves https://github.com/mozilla-iot/gateway/issues/678
We need another cross-compile build here because of noble.
> Add SensorTag adapter

- list.json
> MySensors version 0.0.3

- list.json
- Persistence is now optional
- Node presented is re-request when starting the pairing proces.
- Small improvement to temperature presentation
> MySensors adapter to version 0.0.4

- list.json
> Add telegram-sender-adapter.

- list.json
> Add Medisana KS 250 adapter

- list.json
Adapter for a bluetooth environmental sensor (https://ruuvi.com).
Needs cross-compile build.
> Add RuuviTag adapter

- list.json
- Handles removal of things gracefully
- Avoid using broadcast addresses with Ping
> Presence detection version 0.0.4

- list.json
Adds debug option, trying to find a possible issue that a test user is having.
> MySensors add-on version 0.0.6

- list.json
* removed support for anything different than usb mics
* removed support for personal keyword
* fixed install and uninstall
* updated to latest snips code
* frozen the packages to avoid breaking changes
* bundled a package with all the dependencies
> Version 1.0.0

- list.json
> Update mi-flora-adapter to 0.1.7

- list.json
On Linux `say` needs `Festival` to be installed.
> Add tts adapter

- list.json
More robust handling of exceptions while loading settings.
> MySensors 0.0.8

- list.json
> Add xiaomi temperature humidity sensor adapter

- list.json
- Fixes bug in serial port connection that was introduced in 0.0.8
- rewrites how persistence works in an attempt to fix an issue a user is having.
> MySensors 0.1.0

- list.json
> Add Candle-manager add-on.

- list.json
Still in alpha.
- better management of multiple serial ports.
- more robust handling of edge cases, such as restarting the gateway while viewing the wizard
- fixes bug where MySensors encryption password wasn't set. The encryption code can now be anywhere in the Arduino code.
- added an 'advanced' option which shows power users more details (such as serial port name)
> Candle manager 0.0.4

- list.json
- Better edge case handling
- Many improvements based on feedback from test users
> Candle manager 0.0.5

- README.md
- check-list.py
- list.json
- schema.json
References mozilla-iot/gateway#1973
> Add a new type field.

- list.json
Please consider the ring-adapter for initial release
> Add ring-adapter

- list.json
Can you please add this to https://github.com/mozilla-iot/addon-builder
> Add MAX! adapter

- list.json
I already updated the versions but the addon builder needs to be run and the checksums are outdated.
> Update mi flora adapter to 0.2.1

- list.json
> Add internet-radio.

- list.json
This should fix https://github.com/mozilla-iot/gateway/issues/682 when I'm finished.
Currently only receiving is implemented.
> Add RF433 adapter

- addons/fritz-adapter.json
> Update Fritz! adapter to 0.2.0

- addons/google-home-adapter.json
tim-hellhake/google-home-adapter#7
> Update Google Home adapter to 1.0.0

- addons/fritz-adapter.json
> Update Fritz adapter to 0.2.1

- addons/internet-radio.json
Added requirement for requests module. A user seems to have an issue with it being missing. https://github.com/flatsiedatsie/internet-radio/issues/1
> Internet radio 0.0.3

- addons/voco.json
- Added 'requests' module to requirements list
- Simplified handling of a 'disconnected' error for level values after noticing an issue.
> Voco 0.0.9

- addons/fritz-adapter.json
> Update Fritz! adapter to 0.3.0

- addons/google-home-adapter.json
tim-hellhake/google-home-adapter#4
> Update Google Home adapter to 1.1.0

- addons/fritz-adapter.json
> Update Fritz! adapter to 0.5.0

- addons/gpio-adapter.json
* Add Node 12 version.
* Remove Darwin versions, since adapter is only functional on Linux.
> Update GPIO adapter.

- addons/mi-flora-adapter.json
Please run the addon builder and update the checksums.
tim-hellhake/mi-flora-adapter#12
> Update Mi Flora adapter to 0.2.5

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#3
> Update Systeminfo adapter to 0.2.0

- addons/mi-flora-adapter.json
Please run add builder and add checksums
tim-hellhake/mi-flora-adapter#11
> Update mi flora adapter to 0.3.0

- addons/sensor-tag-adapter.json
Please run addon builder and add checksums
tim-hellhake/sensor-tag-adapter#5
> Update sensor tag adapter to 0.1.2

- addons/fritz-adapter.json
> Update Fritz! adapter to 1.0.0

- addons/openuv-adapter.json
> Update OpenUV adapter to 0.5.1

- addons/sensor-tag-adapter.json
Please run the addon builder and add the new checksums.
tim-hellhake/sensor-tag-adapter#5
> Update sensor tag adapter to 0.1.3

- addons/Candle-manager-addon.json
Tiny change: a single CSS background color, so it now matches the WebThings Gateway.
> Candle Manager 0.0.9

- addons/slack-adapter.json
> Update Slack adapter to 0.2.0

- addons/twitter-adapter.json
tim-hellhake/twitter-adapter#1
> Update twitter adapter to 0.2.0

- addons/sensor-tag-adapter.json
Please run the addon builder and add the new checksums.
tim-hellhake/sensor-tag-adapter#5
> Update sensor tag adapter to 0.1.4

- addons/Candle-manager-addon.json
> Candle Manager 0.0.10

- addons/pushbullet-adapter.json
tim-hellhake/pushbullet-adapter#1
> Update Pushbullet adapter to 0.2.0

- addons/kodi-adapter.json
> Update Kodi adapter to 0.2.0

- addons/azure-iot-bridge.json
tim-hellhake/azure-iot-bridge#2
> Update Azure IoT bridge to 0.1.3

- addons/github-adapter.json
tim-hellhake/github-adapter#2
tim-hellhake/github-adapter#5
tim-hellhake/github-adapter#6
> Update GitHub adapter to 0.1.3

- addons/systeminfo-adapter.json
@mrstegeman Bundle is 90K now 😬
tim-hellhake/systeminfo-adapter#4
> Update Systeminfo adapter to 1.1.0

- addons/lametric-adapter.json
tim-hellhake/lametric-adapter#1
tim-hellhake/lametric-adapter#3
> Update LaMetric adapter to 0.2.0

- addons/voco.json
- tested for 0.10.0 of the Gateway
- More frequent injection of changed names into Snips
- Updated to latest version of Snips
> New version of voco

- addons/pulse-adapter.json
Fixes mozilla-iot/pulse-adapter#7
> Update pulse adapter.

- addons/http-adapter.json
> Update HTTP adapter to 0.4.0

- addons/ruuvitag-adapter.json
Please run the addon builder and add the new checksums.
> Update Ruuvitag adapter to 0.1.3

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#5
> Update systeminfo adapter to 1.1.2

- addons/http-adapter.json
> Update http adapter to 0.4.1

- addons/azure-iot-bridge.json
tim-hellhake/azure-iot-bridge#3
> Update Azure IoT bridge to 0.1.5

- addons/azure-iot-bridge.json
tim-hellhake/azure-iot-bridge#3
> Update Azure IoT bridge to 0.1.6

- addons/tankerkoenig-adapter.json
tim-hellhake/tankerkoenig-adapter#2
> Update Tankerkoenig adapter to 0.2.2

- addons/internet-radio.json
Added manifest.json
Moved persistence location
Made less verbose
> Internet radio 0.0.5

- addons/network-presence-detection-adapter.json
- Added manifest file
- Much improved functionality by using arping. Response time has gone from minutes to seconds, while using much less processing power.
> Presence detecton 0.1.0

- addons/cron-adapter.json
tim-hellhake/cron-adapter#1
tim-hellhake/cron-adapter#2
> Update cron adapter to 0.2.3

- addons/tts-adapter.json
> Update tts adapter to 0.1.4

- addons/luftdaten-adapter.json
tim-hellhake/luftdaten-adapter#1
> Update luftdaten adapter to 0.3.2

- addons/scheduler-adapter.json
tim-hellhake/scheduler-adapter#1
> Update scheduler adapter to 0.1.1

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#6
> Update systeminfo adapter to 1.1.3

- addons/mysensors-adapter.json
Added MQTT topics support
Cloning can now be better controlled: child ID's above 100 will be cloned out into new things.
Better support for S_Power's V_Types.
> MySensors 1.0.2

- addons/esphome-adapter.json
tim-hellhake/esphome-adapter#2
tim-hellhake/esphome-adapter#3
> Update ESPHome adapter to 0.1.1

- addons/network-presence-detection-adapter.json
Tries to hide error messages in logs.
https://github.com/flatsiedatsie/webthings-network-presence-detection/issues/21#issuecomment-564799637
> network presence 0.1.2

- addons/Candle-manager-addon.json
Fixes requirements issue.
https://github.com/createcandle/Candle-manager-addon/issues/6
> Candle manager 1.0.4

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#4
> Update tasmota adapter to 0.1.1

- addons/esphome-adapter.json
tim-hellhake/esphome-adapter#4
> Update esphome adapter to 0.2.0

- addons/voco.json
- Now works with https
- Now stores persistence file in data folder
- Small changes to assistant and functionality (countdown)
> Voco 1.0.1

- addons/voco.json
- Debug was still hardcoded for development
- No longer requires user to set timezone, since the Gateway now allows users to set it.
- Small improvements to the code (routing)
> Voco 1.0.2

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#1
tim-hellhake/shelly-adapter#2
> Update shelly adapter to 0.2.0

- addons/shelly-adapter.json
> Update shelly adapter to 0.2.1

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#5
> Update tasmota adapter to 0.1.2

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#5
> Update tasmota adapter to 0.2.1

- addons/tasmota-adapter.json
Add support for password protected devices (tim-hellhake/tasmota-adapter#4)
> Update tasmota adapter to 0.3.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#6
> Update tasmota adapter to 0.4.1

- addons/xiaomi-temperature-humidity-sensor-adapter.json
Please run the addon builder and add checksums.
tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#5
> Update xiaomi temperature humidity sensor adapter to 0.1.6

- addons/yo-notifier.json
Dev dependencies should be gone now 😄
> Update yo notifier to 0.1.4

- addons/ring-adapter.json
Added ability to control lights and sirens.  Fixed broken ring api library.
> Update version 0.0.3

- addons/tradfri-adapter.json
Please add the adapter to the addon builder and add the checksums.
tim-hellhake/tradfri-adapter#1
> Update tradfri adapter to 0.1.3

- addons/insteon-adapter.json
> Add insteon-adapter-1.0.0

- addons/miLight-adapter.json
> Add miLight adapter.

- addons/prowl-adapter.json
> Update prowl adapter to 0.2.1

- addons/myq-adapter.json
Adds a new MyQ adapter for Chamberlain garage doors
> New MyQ Adapter

- addons/google-home-adapter.json
tim-hellhake/google-home-adapter#8
> Update google home adapter to 1.1.1

- addons/prowl-adapter.json
> Update prowl adapter to 0.2.2

- addons/netatmo-weather-adapter.json
tim-hellhake/netatmo-weather-adapter#7
> Update netatmo weather adapter to 0.3.6

- addons/power-settings.json
For for reboot issue https://github.com/mozilla-iot/gateway-addon-python/issues/80
> power settings 0.0.2

- addons/opensensemap-adapter.json
tim-hellhake/opensensemap-adapter#1
> Update opensensemap adapter to 0.1.1

- addons/generic-sensors-adapter.json
Bug: https://github.com/rzr/mozilla-iot-generic-sensors-adapter/issues/11
Relate-to: https://github.com/mozilla-iot/addon-list/pull/54
Change-Id: I576648a50ba66abe91688359abdfa281a0ae63fa
> generic-sensors-adapter: Update to v0.0.10

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#7
> Update systeminfo adapter to 1.2.0

- addons/sonos-adapter.json
> Update sonos updater to 0.7.6

- addons/activitypub-adapter.json
Change-Id: Iace96f5b9b435bec3f193a9fc2ed161f573c0bfa
Relate-to: https://github.com/mozilla-iot/addon-list/pull/158
Bug: https://github.com/rzr/mastodon-lite/issues/12
> activitypub: Update to 0.0.18

- addons/homematic-adapter.json
tim-hellhake/homematic-adapter#3
> Update homematic adapter to 0.1.3

- addons/medisana-ks250-adapter.json
Please run the addon builder and add checksums.
tim-hellhake/medisana-ks250-adapter#5
> Update medisana ks250 adapter to 0.1.4

- addons/netatmo-weather-adapter.json
tim-hellhake/netatmo-weather-adapter#8
> Update netatmo weather adapter to 0.3.7

- addons/sipgate-adapter.json
tim-hellhake/sipgate-adapter#1
> Update sipgate adapter to 0.2.1

- addons/rf433-adapter.json
Please run the addon builder and add the checksum.
tim-hellhake/rf433-adapter#2
> Update rf433 adapter to 0.1.3

- addons/enocean-adapter.json
Please run the addon builder and add the checksums.
https://github.com/tim-hellhake/enocean-adapter/issues/7
> Update enocean adapter to 0.1.6

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#11
> Update tasmota adapter to 0.4.2

- addons/Candle-manager-addon.json
Fully tested to work with http and https.
> Candle manager 1.0.6

- addons/square-theme.json
- Improved centering
- Chromium scroll issue fix
> Square theme update

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#15
> Update tasmota adapter to 0.5.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#8
> Update tasmota adapter to 0.5.1

- addons/tankerkoenig-adapter.json
tim-hellhake/tankerkoenig-adapter#3
> Upadate tankerkoenig adapter to 0.2.3

- addons/power-settings.json
small fix for stray .pyc file issue:
https://github.com/flatsiedatsie/power-settings/issues/2
> Power settings 0.0.3

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#16
> Update tasmota adapter to 0.6.0

- addons/tradfri-adapter.json
tim-hellhake/tradfri-adapter#3
> Update tradfri adapter to 0.2.0

- addons/date-time-adapter.json
> Update DateTime adapter

- addons/sipgate-adapter.json
tim-hellhake/sipgate-adapter#2
> Update sipgate adapter 0.2.3

- addons/medisana-ks250-adapter.json
tim-hellhake/medisana-ks250-adapter#6
> Update medisana ks250 adapter to 0.1.5

- addons/mysensors-adapter.json
Fixed issue with string being treated as numbers, and leading zero's being stripped off.
> MySensors 1.0.6

- addons/timer-adapter.json
> Update timer adapter to 1.2.2

- addons/enocean-adapter.json
tim-hellhake/enocean-adapter#9
> Update enocean adapter to 0.1.7

- addons/activitypub-adapter.json
Origin: https://github.com/CrossStream/addon-list/tree/sandbox/rzr/review/master
Forwarded: https://github.com/mozilla-iot/addon-list/pull/
Change-Id: Id26f01759e10d0d231df70c6952dbdc48937fa14
> activitypub: Update to 0.0.19

- addons/timer-adapter.json
> Update timer to 1.3.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#19
> Update tasmota adapter to 0.7.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#19
> Update tasmota adapter to 0.8.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#23
tim-hellhake/tasmota-adapter#24
> Update tasmota adapter to 0.8.1

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#7
> Update ruuvitag adapter to 0.1.4

- addons/frontier-silicon-adapter.json
> Add frontier-silicon-adapter.

- addons/prowl-adapter.json
> Update prowl adapter to 0.2.4

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#20
> Update tasmota adapter to 0.9.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#10
tim-hellhake/tasmota-adapter#15
> Update tasmota adapter to 0.10.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#22
> Update tasmota adapter to 0.11.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#17
> Update tasmota adapter to 0.12.0

- addons/shelly-adapter.json
> Update shelly adapter to 0.3.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#25
> Update tasmota adapter to 0.13.0

- addons/shelly-adapter.json
> Update shelly adapter to 0.3.1

- addons/shelly-adapter.json
> Update shelly adapter to 0.3.2

- addons/shelly-adapter.json
> Update shelly adapter to 0.4.1

- addons/shelly-adapter.json
> Update shelly adapter to 0.5.0

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#8
> Update systeminfo adapter to 1.3.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#21
> Update tasmota adapter to 0.14.0

- addons/mysensors-adapter.json
- After starting to use a zigbee USB stick, I encountered some odd behaviour where incoming messages would stop after a few days. This is an attempt to fix it.
- Secondly, it now allows the Candle receiver to also be a thing.
- It also improves some other minor things, such as the clock thread.
> MySensors 1.0.8

- addons/Candle-manager-addon.json
Another attempt to quick-fix the SSL issue. The next big step will be to completely rewrite the add-on to use the API system.
> Candle Manager 1.0.8

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#10
> Update systeminfo adapter to 1.5.0

- addons/zmote-adapter.json
> Add zmote adapter

- addons/zmote-adapter.json
> Update zmote adapter to 0.2.0

- addons/timer-adapter.json
> Update timer to 1.3.1

- addons/timer-adapter.json
> Update timer adapter to 1.4.0

- addons/luftdaten-adapter.json
tim-hellhake/luftdaten-adapter#2
> Update luftdaten adapter to 0.3.3

- addons/luftdaten-adapter.json
tim-hellhake/luftdaten-adapter#2
> Update luftdaten adapter to 1.0.0

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#3
> Update spotify adapter

- addons/luftdaten-adapter.json
tim-hellhake/luftdaten-adapter#3
> Update luftdaten adapter to 1.1.0

- addons/piface-adapter.json
Please add the piface adapter to the addon build and update the checksum.
> Add piface adapter

- addons/shelly-adapter.json
> Update shelly adapter to 0.6.0

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#10
> Update spotify adapter to 0.2.1

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#10
> Update shelly adapter to 0.7.0

- addons/counter-adapter.json
tim-hellhake/counter-adapter#4
> Update counter adapter to 0.3.3

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#7
> Update spotify adapter to 0.2.2

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#11
> Update shelly adapter to 1.0.0

- addons/counter-adapter.json
tim-hellhake/counter-adapter#5
> Update counter adapter to 0.3.4

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#3
> Update spotify adapter to 0.2.3

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#13
> Update spotify adapter to 0.2.5

- addons/generic-sensors-adapter.json
> generic-sensors: Update to 0.0.13 from 0.0.12

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#13
> Update spotify adapter to 0.3.0

- addons/sense-hat-adapter.json
Change-Id: I7bca3477e10b4808c0c13358e553d734ab318301
Relate-to: https://github.com/rzr/sense-hat-webthing/issues/3
> sensehat: Update to 0.0.4 from 0.0.3

- addons/github-adapter.json
> Update GitHub adapter to 0.1.6

- addons/kafka-bridge.json
> Add kafka bridge

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#27
> Update tasmota adapter to 0.15.0

- addons/sense-hat-adapter.json
Bug: https://github.com/rzr/sense-hat-webthing/issues/3
I will update checksum once urls are reachable
> sense-hat-adapter: Update to 0.0.7

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#18
> Update spotify adapter to 0.4.2

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#19
> Update spotify adapter to 0.4.3

- addons/cron-adapter.json
> Update cron adapter to 0.2.4

- addons/influxdb-bridge.json
Please add it to the addon-builder and update the checksums
> Add influxdb bridge

- addons/cron-adapter.json
> Update cron adapter to 0.2.5

- addons/network-presence-detection-adapter.json
Small fix for brute force scan issue reported by users.
> Network presence 0.1.3

- addons/timer-adapter.json
> Update timer adapter to 1.5.0

- addons/power-settings.json
- reboot option also reloads page after 30 seconds
- better CSS on touch UI
> power settings 0.0.4

- addons/ruuvitag-adapter.json
https://github.com/tim-hellhake/ruuvitag-adapter/issues/10
> Update ruuvitag adapter (addon-builder)

- addons/photo-frame.json
- Added a clock
- Added touch-screen keep-awake feature
- Some small CSS improvements
- Some cleanup
> Photo frame 0.0.2

- addons/network-presence-detection-adapter.json
> Network presence 1.0.0

- addons/square-theme.json
- better use of space on 1024x600 touch screen
- improved usability of addon settings pages
> Square theme 0.0.4

- addons/square-theme.json
> Square theme 0.0.5

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#13
> Update ruuvitag adapter to 0.3.0

- addons/timer-adapter.json
tim-hellhake/timer-adapter#11
tim-hellhake/timer-adapter#12
> Update timer adapter to 1.6.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#30
> Update tasmota adapter to 0.16.0

- addons/influxdb-bridge.json
tim-hellhake/influxdb-bridge#2
> Update influx bridge to 0.3.0

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#14
tim-hellhake/ruuvitag-adapter#16
> Update ruuvitag adapter to 0.3.1

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#19
> Update ruuvitag adapter to 0.3.2

- addons/mysensors-adapter.json
> MySensors 1.1.0

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#18
> Update ruuvitag adapter to 0.4.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#28
> Update tasmota adapter to 0.18.0

- addons/airport.json
Stream audio or even your desktop to your gateway over Airplay.
> Initial creation of Airport addon

- addons/Candle-manager-addon.json
fixes small issue where update process could run twice at the same time.
> Candle manager 1.1.0

- addons/matrix-adapter.json
* Resolve room aliases
* Auto-join upgraded rooms (configurable)
> Update addon: Matrix 0.3.2

- addons/calendar.json
This adapter provides calendar management of the working week, holidays, and other event dates. This is to support rules such as not switching on a wakeup alarm on public or personal holidays, or triggering an automatic light display on a birthday.
First release
- a singleton thing
- 4 Properties
-- isHoliday
-- isWorkingDay
-- reason (for date significance)
-- rulesTag (may be useful for rules)
- updated each day (checked each hour, to allow for timezones, daylight savings)
- configuration sheet to setup working week and significant dates (holidays, vacations, etc)
> first release of calendar adapter

- addons/internet-radio.json
Fixes that the radio automatically started at boot
> internet radio 1.1.1

- addons/calendar.json
adds holidays from Calendarific.com API
defensive fixes for first time use with no configuration
> calendar-0.1.2

- addons/voco.json
- Reverting to aplay for quicker response time, while keeping the relative volume level feature. To make this possible, each audio file now has versions at different volume levels.
- Extra voice settings  for accent, pitch and speed. In a way this allows users to choose a male or female voice.
- Less verbose in internal logs. This also improves privacy.
> Voco 1.1.2

- addons/calendar.json
added source property to show where the date came from
improved handling of other text properties
> publish Calendar-0.1.3

- addons/calendar.json
- add 2nd holiday API provider
- code reorganisation
- show day name in description property if there is no other reason
> calendar-0.2.0

- addons/timer-adapter.json
> Update timer adapter to 1.6.1

- addons/sonos-adapter.json
> Update sonos adapter to 0.9.1

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#22
> Update ruuvitag adapter to 0.4.1

- addons/calendar.json
- more careful handling of configuration updates
- documentation updates
> calendar v0.2.1

- addons/voco.json
- Voco files are no longer zipped (thanks to MrStegeman)
- fixes countdown
- general cleanup - less verbose.
> Voco 1.1.3

- addons/followers.json
This addon allows one property to respond to a changing value of another. For example, as one value rises, another value could also be made to rise. Or it could be made to slowly decrease instead. 
It adds funtionality that cannot currently be easily created through the rules system.
If the rules system every gains this functionality, then this addon could be removed.
See also the "property to property" issue: https://github.com/mozilla-iot/gateway/issues/805
> Initial release of Followers

- addons/followers.json
fixes sorting bug which could create frankenstein properties
> followers 0.0.3

- addons/followers.json
- better handling of situation where source value does not have a value yet (e.g. after gateway reboot)
> Followers 0.0.4

- addons/followers.json
Now handles properties that only accept integers
> Follower 0.1.0

- addons/tradfri-adapter.json
tim-hellhake/tradfri-adapter#8
> Update tradfri adapter to 0.2.3

- addons/followers.json
Fixes https://github.com/flatsiedatsie/followers-addon/issues/1
> Followers 0.1.1

- addons/calendar.json
version v0.3.0
- introduce annual events
- reduce unnecessary updates to configuration
- migrate deprecated config settings, and remove
- update dependencies
> calendar-v0.3.0

- addons/followers.json
PRevious issue wasn't fixed. PYC files were still being included, as were hidden files. No longer!
> Followers 0.1.2

- addons/square-theme.json
- Adds log overlay feature. After selecting which logs to show, pressing the 'overlay' button will overlay them on top of eachother.
> Square theme 1.0.1

- addons/followers.json
potential fix for https://github.com/flatsiedatsie/followers-addon/issues/3
> Followers 0.1.3

- addons/calendar.json
- added 3rd holiday API provider - holidays.abstractapi.com
- code cleanups and documentation updates
- version bump to indicate 'complete', subject to review comments if any
> calendar-v0.9.0

- addons/voco.json
> Voco 1.1.4

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#14
tim-hellhake/systeminfo-adapter#15
> Update systeminfo adapter to 1.6.0

- addons/photo-frame.json
- improves clock
- hides file upload options in full screen mode (kiosk)
> Photo frame 0.0.3

- addons/tradfri-adapter.json
tim-hellhake/tradfri-adapter#8
tim-hellhake/tradfri-adapter#9
> Update tradfri adapter to 0.3.0

- addons/tradfri-adapter.json
tim-hellhake/tradfri-adapter#9
> Update tradfri adapter to 0.4.0

- addons/pushbullet-adapter.json
tim-hellhake/pushbullet-adapter#6
> Update pushbullet adapter to 0.2.2

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#12
> Update systeminfo adapter to 1.7.0

- addons/voco.json
Trying to squash issue https://github.com/createcandle/voco/issues/8
> Voco 1.1.5

- addons/followers.json
- simpler code
- toggle of new item works better
> Followers 0.2.0

- addons/internet-radio.json
Makes sure audio_output is in persistence data
> Internet radio 1.1.2

- addons/network-presence-detection-adapter.json
Attempt to limit CPU usage https://github.com/flatsiedatsie/webthings-network-presence-detection/issues/27
> Network presence detection adapter 1.0.1

- addons/voco.json
Fix for voice issue on Raspberry Pi 3 https://github.com/createcandle/voco/issues/8
> Voco 1.2.0

- addons/followers.json
Fixed issue with deleted item re-appearing when pressing add button
> Followers 0.3.0

- addons/network-presence-detection-adapter.json
Another attempt to fix high CPU usage. https://github.com/flatsiedatsie/webthings-network-presence-detection/issues/27
> Network presence detection adapter 1.0.2

- addons/highlights.json
> Highlights 0.0.2

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#18
> Update systeminfo adapter to 1.8.0

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#18
tim-hellhake/systeminfo-adapter#19
> Update systeminfo adapter to 1.9.0

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#11
> Update systeminfo adapter to 1.10.0

- addons/calendar.json
add event to report API errors
> calendar-v1.0.0

- addons/psi-sg.json
- add event to report API errors
- fix creation of duplicate devices
- automate builds and releases
- re-install dev dependencies after packaging
- bump dependencies
> psi-sg-v0.9.1

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#32
> Update tasmota adapter to 1.1.0

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#24
> Update ruuvitag adapter to 0.5.0

- addons/followers.json
Small fix for potential database issue
> Followers 0.3.1

- addons/influxdb-bridge.json
tim-hellhake/influxdb-bridge#3
tim-hellhake/influxdb-bridge#4
> Update influxdb bridge to 0.4.0

- addons/voco.json
- Adds a UI that show an overview of active timers, reminders and alarms
- Adds easy to use satellite functionality, where multiple gateway can link together.
- Adds USB microphone hot-plug functionality
- Fixed various small bugs and imperfections found while creating the features above
> Voco 2.0.0

- addons/netatmo-weather-adapter.json
tim-hellhake/netatmo-weather-adapter#9
> Update netatmo weather adapter to 0.4.0

- addons/voco.json
Removes some left over logging output that slipped through
> Voco 2.0.1

- addons/highlights.json
- removed permanent debugging error
- scroll to bottom when adding item
> Highlights 0.1.0

- addons/followers.json
- scroll to bottom after ading new item
- less verbose javascript
> Followers 0.4.0

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#9
> Update systeminfo adapter to 1.10.1

- addons/kafka-bridge.json
> Update kafka bridge to 0.1.1

- addons/voco.json
Yikes, sorry about that: the previous version wasn't perfect, so I was fixing it and left the incomplete pull request up.
> Voco 2.2.1

- addons/voco.json
- Remove newline from token
- Satellite functionality now also works on a Raspberry Pi Zero
> Voco 2.2.2

- addons/enocean-adapter.json
tim-hellhake/enocean-adapter#12
> Update enocean adapter

- addons/modbus-adapter.json
> Add modbus adapter

- addons/psi-sg.json
provide a link on the thing to the source of the data, update the README
> psi-sg-v1.0.0

- addons/ttn-adapter.json
> Update ttn adapter to 0.2.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#34
> Update tasmota adapter to 1.1.1

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#33
> Update tasmota adapter to 1.1.2

- addons/psi-sg.json
> psi-sg-v1.0.1

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#29
> Update tasmota adapter to 2.0.0

- addons/powerwall-adapter.json
> Add Tesla Powerwall adapter.

- addons/purpleair-adapter.json
tim-hellhake/purpleair-adapter#1
> Update purpleair adapter to 0.1.1

- addons/calendar.json
> calendar-v1.1.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#35
> Update tasmota adapter to 2.0.1

- addons/dmx-adapter.json
> Add dmx adapter

- addons/psi-sg.json
> psi-sg-v1.0.2

- addons/calendar.json
> calendar-v1.1.1

- addons/fritz-adapter.json
tim-hellhake/fritz-adapter#6
tim-hellhake/fritz-adapter#7
> Update fritz adapter

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#17
> Update shelly adapter to 1.0.1

- addons/slack-adapter.json
> Update slack adapter to 0.2.3

- addons/activitypub-adapter.json
Relate-to: https://github.com/WebThingsIO/addon-list/pull/158
> activitypub-adapter: Update to 0.0.23

- addons/counter-adapter.json
tim-hellhake/counter-adapter#2
> Update counter adapter to 0.3.5

- addons/fritz-adapter.json
> Update fritz adapter to 1.2.0

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#35
> Update tasmota to 2.0.2

- addons/tasmota-adapter.json
tim-hellhake/tasmota-adapter#35
> Update tasmota adapter to 2.0.3

- addons/piface-adapter.json
> Update piface adapter to 0.1.1

- addons/xiaomi-temperature-humidity-sensor-adapter.json
tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#7
tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#8
tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#10
> Update xiaomi-temperature-humidity-sensor-adapter to 0.2.0

- addons/fritz-adapter.json
> Update fritz-adapter to 1.3.0

- addons/awox-mesh-light-adapter.json
Relate-to: https://github.com/WebThingsIO/addon-list/pull/851
Forwarded: https://github.com/WebThingsIO/addon-list/pulls/rzr
Change-Id: I01f4a40ac08d28d5b05b46a5bc23562a151ce894
> awox-mesh-light-adapter: Update to 0.0.8

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#18
> Update shelly-adapter to 1.0.2

- addons/fritz-adapter.json
> Update fritz-adapter to 2.0.1

- addons/fritz-adapter.json
> Update fritz-adapter to 2.1.0

- addons/http-adapter.json
> Update http-adapter to 0.5.0

- addons/http-adapter.json
> Update http-adapter to 0.6.0

- addons/http-adapter.json
> Update http-adapter to 0.7.0

- addons/homie-adapter.json
> Update homie-adapter to 0.2.3

- addons/fritz-adapter.json
> Update fritz-adapter to 2.2.0

- addons/fritz-adapter.json
> Update fritz-adapter to 2.3.0

- addons/modbus-adapter.json
> Update modbus-adapter to 0.3.0

- addons/airport.json
- Fix missing file https://github.com/flatsiedatsie/airport/issues/2
- Implement cleanup
> Airport 0.0.5

- addons/netatmo-weather-adapter.json
tim-hellhake/netatmo-weather-adapter#11
tim-hellhake/netatmo-weather-adapter#12
> Update netatmo-weather-adapter to 0.5.0

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#13
tim-hellhake/shelly-adapter#16
> Update shelly-adapter to 1.2.0

- addons/opensensemap-adapter.json
tim-hellhake/opensensemap-adapter#4
> Update opensensemap-adapter to 0.1.2

- addons/opensensemap-adapter.json
tim-hellhake/opensensemap-adapter#5
> Update opensensemap-adapter to 0.1.3

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#20
> Update shelly-adapter to 1.3.0

- addons/modbus-adapter.json
> Update modbus-adapter to 0.4.0

- addons/timer-adapter.json
> Update timer-adapter to 1.6.2

- addons/sonos-adapter.json
> Update sonos-adapter to 0.9.2

- addons/sonos-adapter.json
> Update sonos-adapter to 0.9.3

- addons/airport.json
Modifications for Webthings 1.0
> Airport 0.1.0

- addons/network-presence-detection-adapter.json
> network presence detector 1.1.1

- addons/internet-radio.json
> Internet Radio 1.1.4

- addons/voco.json
> Voco 2.2.5

- addons/voco.json
> Voco 2.2.6

- addons/airport.json
> Airport 0.1.1

- addons/photo-frame.json
> Photoframe 1.0.1

- addons/sonos-adapter.json
> Update sonos-adapter to 0.10.0

- addons/purpleair-adapter.json
tim-hellhake/purpleair-adapter#3
> Update purpleair-adapter to 1.2.1

- addons/esphome-adapter.json
tim-hellhake/esphome-adapter#10
> Update esphome-adapter to 0.2.2

- addons/xiaomi-temperature-humidity-sensor-adapter.json
tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#12
> Update xiaomi-temperature-humidity-sensor-adapter to 0.2.1

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#11
tim-hellhake/spotify-adapter#15
tim-hellhake/spotify-adapter#20
> Update spotify-adapter to 0.6.0

- addons/psi-sg.json
- error handling when api delivers 'empty' results
- WebThings rebranding
- bump dependencies
- dev: automate finding updated dependencies and updated  github actions
> psi-sg-v1.1.2

- addons/calendar.json
- WebThings rebranding
- update dependencies
- dev: automate finding updated dependencies and github actions
> calendar-v1.1.5

- addons/fritz-adapter.json
> Update fritz-adapter to 2.3.2

- addons/spotify-adapter.json
tim-hellhake/spotify-adapter#20
> Update spotify-adapter to 0.6.1

- addons/mysensors-adapter.json
JSON generated using the new tool
> MySensors 1.2.3

- addons/voco.json
- fixes issue where complex thing titles could not be learnt properly
- new feature to allow text input as well
- assistants are finally stable
> Voco 2.5.2

- addons/voco.json
- Adds audio samplerate feature to (hopefully) fix issues with Jabra USB speakers (for @kgiori)
- Improves name injection. Improves controlling devices around the home that may be distributed over many WebThings Gateway instances.
- Fixes issue where dropdown values could not be properly controlled (thanks to @mrstegeman)
> Voco 2.5.3

- addons/modbus-bridge.json
> Add modbus bridge

- addons/Candle-manager-addon.json
Shamefull error.. The requirements file was accidentally the wrong one, from the mysensors addon. Hence all the issue reports.
> Candle manager 1.1.7

- addons/internet-radio.json
> Internet radio 1.1.7

- addons/voco.json
Small impovement in ability to restart Snips if it stops/crashes somehow.
> Voco 2.5.4

- addons/power-settings.json
Fixes odd positioning on small displays
> Power Setting 1.0.5

- addons/square-theme.json
Fix for issue with property overview page in Safari
> Square theme 1.0.3

- addons/dingz-adapter.json
- addons/maxsmart2-adapter.json
Two new adapters, well one really new adapter. Both of them are for rather Switzerland specific products, one of which is no longer even sold...
> Dingz and maxsmart2 adapters

- addons/dingz-adapter.json
Of course I forgot to include a file in the package. As first releases for adapters go that seems pretty standard.
> Dingz adapter 0.2.2

- addons/zigbee2mqtt-adapter.json
Fixes and improves firmware update feature
> Zigbee2MQTT 0.5.0

- addons/kafka-bridge.json
> Update kafka-bridge to 0.2.0

- addons/mysensors-adapter.json
Fixes issue with new color support
> MySensors 1.2.4

- addons/followers.json
Extra check if properties exist
> Followers 0.5.4

- addons/square-theme.json
- remove empty logs from log filter list
- dark background color for Data transmission property
> Square theme 1.0.4

- addons/voco.json
Works better with the zigbee2mqtt addon
> Voco 2.5.9

- addons/zigbee2mqtt-adapter.json
Additional properties weren't being added
> Zigbee2MQTT 0.6.1

- addons/voco.json
More complex thing scanner, now weighs some capabilities in choosing which property to output (needed for Zigbee2MQTT addon)
> Voco 2.6.0

- addons/dmx-adapter.json
> Update dmx-adapter to 0.1.3

- addons/mysensors-adapter.json
https://github.com/createcandle/Webthings-mysensors-adapter/issues/21
> MySensors 1.2.6

- addons/sonos-adapter.json
> Update sonos-adapter to 0.11.0

- addons/voco.json
An attempt to fix https://github.com/createcandle/voco/issues/21
> Voco 2.6.1

- addons/influxdb-bridge.json
tim-hellhake/influxdb-bridge#8
> Update influxdb-bridge to 0.5.0

- addons/square-theme.json
Adds rules scrollable tray feature
> Square theme 1.0.5

- addons/influxdb-bridge.json
tim-hellhake/influxdb-bridge#8
> Update influxdb-bridge to 0.5.1

- addons/Candle-manager-addon.json
Fixes permission not being set properly for arduino cli https://github.com/createcandle/Candle-manager-addon/issues/32
> Candle Manager 1.1.9

- addons/Candle-manager-addon.json
Attempt to fix https://github.com/createcandle/Candle-manager-addon/issues/33
> Candle manager 1.2.2

- addons/psi-sg.json
- display the earlier of the two message timestamps
> PSI-SG v1.4.1

- addons/wled-adapter.json
tim-hellhake/wled-adapter#1
tim-hellhake/wled-adapter#2
tim-hellhake/wled-adapter#3
> Update wled-adapter to 0.3.0

- addons/kafka-bridge.json
> Update kafka-bridge to 0.4.0

- addons/kafka-bridge.json
> Update kafka-bridge to 0.5.0

- addons/Candle-manager-addon.json
- Fix for changed Arduino CLI
- Actual fix for arduino cli permission issue
> Candle manager 1.2.4

- addons/psi-sg.json
- always update values even if unchanged to improve downstream graphing
> psisg-v1.4.2

- addons/date-time-adapter.json
for other contributors to have input on this project as desired, including the original, tomasy.
> Moved from wfahle to WTIOAddons 

- addons/azure-iot-bridge.json
tim-hellhake/azure-iot-bridge#7
> Update azure-iot-bridge to 1.1.0

- addons/azure-iot-bridge.json
tim-hellhake/azure-iot-bridge#7
> Update azure-iot-bridge to 1.2.0

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#22
> Update shelly-adapter to 1.4.0

- addons/date-time-adapter.json
> Release 113

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#22
> Update shelly-adapter to 1.5.0

- addons/systeminfo-adapter.json
tim-hellhake/systeminfo-adapter#17
tim-hellhake/systeminfo-adapter#23
> Update systeminfo-adapter to 1.11.0

- addons/philips-hue-adapter.json
WebThingsIO/philips-hue-adapter#25
WebThingsIO/philips-hue-adapter#66
> Update philips-hue-adapter to 1.0.3

- addons/konnected-adapter.json
> Release konnected 0.0.4

- addons/Candle-manager-addon.json
Attempt to fix an issue for a user.
https://github.com/createcandle/Candle-manager-addon/issues/35
> Candle manager 1.2.6

- addons/konnected-adapter.json
Added access code for arm/disarm of adapter.
> Added access code to Konnected adapter

- addons/prometheus-bridge.json
tim-hellhake/prometheus-bridge#2
> Update prometheus-bridge to 0.5.0

- addons/zigbee-adapter.json
WebThingsIO/zigbee-adapter#292
> Update zigbee-adapter to 0.20.0

- addons/modbus-bridge.json
github.com/tim-hellhake/modbus-bridge#3
> Update modbus-bridge to 0.2.1

- addons/ruuvitag-adapter.json
tim-hellhake/ruuvitag-adapter#17
tim-hellhake/ruuvitag-adapter#26
> Update ruuvitag-adapter to 0.7.0

- addons/zigbee-adapter.json
WebThingsIO/zigbee-adapter#308
> Update zigbee-adapter to 0.21.0

- addons/zigbee-adapter.json
WebThingsIO/zigbee-adapter#308
WebThingsIO/zigbee-adapter#314
> Update zigbee-adapter to 0.21.1

- addons/dingz-adapter.json
Adds support for firmware v1.3
> dingz-adapter 0.3.0

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#25
> Update shelly-adapter to 1.6.0

- addons/shelly-adapter.json
tim-hellhake/shelly-adapter#27
> Update shelly-adapter to 1.7.0

- addons/date-time-adapter.json
Fixed a bug in sunset offset calculations (next sunset and next sunrise) when day is getting shorter
> fixed sunset offset 1.1.4

- addons/dingz-adapter.json
Bug fixes around the connection state of the devices
> dingz-adapter 0.3.1

- addons/zigbee2mqtt-adapter.json
https://github.com/kabbi/zigbee2mqtt-adapter/issues/41
> potential fix for issue #41

- addons/webtio-hydroqc-addon.json
> Webtio hydroqc addon v0.2 beta

- addons/webtio-hydroqc-addon.json
> update webtio-hydroqc-addon to 0.1.3

- addons/date-time-adapter.json
> Release 1.1.6 date-time-adapter

- addons/date-time-adapter.json
Limited ability to test, please expedite this fix.
> Fixed broken date time adapter for all

- addons/denon-adapter.json
Got to it earlier than expected. Took the opportunity to clean up the bundle and update deps a bit.
> Bump denon-adapter to v1.0.1

- addons/date-time-adapter.json
This time I will not break anything, but have fixed the actual issue with 33,12 as a lat/long. It will now be accepted. No rush on this one.
> Fixed original bug (and tested)

- addons/netatmo-energy-adapter.json
@tim-hellhake sorry about that, unfortunately had to create another release
> Another netatmo-energy-adapter update to 3.0.2
