WebThingsIO/addon-list

- list.json
Tested on my RPi 3 using the 0.3.0 image.
> Bump zigbee adapter to 0.3.1

- list.json
This is an interesting adapter:
it actually uses a REST API to a proprietary server (from the device manufacturer) to represent local devices. Further, in theory device properties are read-only, not that that's something that you can currently explicitly represent from what I can tell.
> Add netatmo weather station adapter

- list.json
Note that arm package was built using docker + binfmt (on x86_64)
Change-Id: If5e3084e33aed2a918b45349a98ca9505c676bd7
Origin: https://github.com/TizenTeam/addon-list
> generic-sensors-adapter: Update to 0.0.3

- list.json
The chromecast adapter gets support for play/pause and everything gets turned into properties. Will break existing things that are added in the gateway...
The sonos adapter now knows how volumes work again for the 0.5 gateway.
> Update chromecast and sonos adapter

- list.json
There was an issue installing these inside Docker containers that
has now been fixed.
> Bump eufy, homekit, and wemo.

- list.json
Since the min api was bumped to 2, I also removed the old URL.
> Bump zigbee-adapter to 0.6.1

- list.json
Added 2 new properties `Hour_N` and `Minute_N`. To create rules valid only between some time. See mozilla-iot/gateway#1475
It would be nice if it exist a link to a changelog file
> DateTime 0.9.5

- update.py
If you provide an adapter name which doesn't exist
then the script would fail.
> Fix bug where invalid adapter name is provided

- list.json
- Add cover art property to sonos
- Switch to better IDs for sonos (no migration, this is pre-release software, I guess)
- Improve initialization error handling
- Try to recover when the connection to devices is interrupted
- Make starting flicd optional
> Update my adapters with the following improvements:

- list.json
Source: https://github.com/rzr/mastodon-lite/releases/tag/v0.0.9
Relate-to: https://github.com/mozilla-iot/addon-list/pull/158
Change-Id: I5e793046df49dd7d88e5733749bf6c3fbffce4d5
> Update activitypub-adapter to 0.0.9

- list.json
Now with color sensor to be used for "WoTxR" PoC
Source: https://github.com/rzr/mozilla-iot-generic-sensors-adapter/releases/tag/v0.0.6
Relate-to: https://github.com/mozilla-iot/addon-list/pull/54
Forwarded: https://github.com/mozilla-iot/addon-list/pull
Change-Id: Icb6c01bac3d59a6027843fbccd1d0a846d689721
> Update generic-sensors-adapter to 0.0.6

- list.json
This should make it so the adapter doesn't lock up the gateway, or is at least a lot less likely to.
> Update chromecast adapter

- list.json
This is an adapter for a pretty obscure smart plug that probably only exists in Switzerland in this form (due to Switzerland having its own plug system). It's likely though, that there are other plugs using a similar protocol, made originally by Revogi and possibly rebranded...
> Add maxSMART 2.0 Adapter

- list.json
Fixes id, then things can be propertly removed.
ARMv8 support added
Change-Id: I8bc80fb16d5c2b3145e111f0e0ce772b9b4fd798
Relate-to: https://github.com/mozilla-iot/addon-list/pull/206
> Update generic-sensors-adapter to 0.0.7

- list.json
Set i2c drivers as default, simulators can be added from GUI
Change-Id: I4938f6cab2b6d800024d870f060fa63d75272223
Relate-to: https://github.com/mozilla-iot/addon-list/pull/206
> Update generic-sensors-adapter to 0.0.8

- list.json
Getting closer to a 1.0 release.
- Expanded support for MySensors types
- More careful implementation of Mozilla's IoT schema capabilities
- Persistence as you would expect it: if enabled, all things are immediately re-created after a reboot of the gateway.
- Proper support for removing devices. They are cleared from the persistence as well.
> Upgrade to version 0.0.5

- list.json
Fixes issue where preferred capability to display centrally was forgotten on add-on restart.
Also, the persistence feature has been replaced with an option to show a device as connected only after some signal has been received.
> MySensors to 0.0.7

- list.json
Fixing logging features, simplified config
Test with simulators:
https://hub.samsunginter.net/adding-sensors-to-the-web-of-things/
Relate-to: https://github.com/mozilla-iot/addon-list/pull/54
Change-Id: Ib917be0a948036530fb5ed947ab1139899309cc3
> Update generic-sensors-adapter to v0.0.9

- list.json
Change-Id: Ifc7bfe0a46495cfd06fa2bb707bb1f55ea60ed82
Relate-to: https://github.com/mozilla-iot/addon-list/pull/158
> Update activitypub adapter to 0.0.14

- list.json
Adds Title support.
Various other improvements, mostly for the 'advanced' option.
Fixes edge case where a double click could start two simultaneous processes, resulting in errors.
> Candle manager 0.0.6

- list.json
I already updated the versions but the addon builder needs to be run and the checksums are outdated.
> Update mi flora adapter to 0.2.0

- list.json
- Automatic serial port searching. User doesn't need to add a serial port ID manually anymore (but can if they want)
- Support for metric/imperial units. You can set your preference in the add-on settings.
- Support for multipleOf. This should help show a sane amount of decimals on numeric variables.
- Experimental MQTT support based on user feedback
- Anticipates switch to version 0.9 of the WebThings gateway by implementing title support.
> MySensors version 0.1.2

- list.json
This hasn't been touched in ages and shouldn't be necessary
since webthing-arduino exists.
In other cases, the http-adapter should be sufficient.
> Remove old http-on-off-adapter.

- addons/mi-flora-adapter.json
I already updated the versions but the addon builder needs to be run and the checksums are still missing.
tim-hellhake/mi-flora-adapter#8
> Update Mi Flora adapter to 0.2.2

- addons/xiaomi-temperature-humidity-sensor-adapter.json
Addon builder needs to be run and checksums are missing
> Update Xiaomi Bluetooth Temperature and Humidity Sensor adapter to 0.1.4

- addons/Candle-manager-addon.json
- better handling of gateway 0.10.0 code on older versions of the gateway
- gateway.local link in thing is no longer hardcoded, but reflects actual LAN ip address.
> Candle manager version 1.0.0

- addons/Candle-manager-addon.json
- Doesn't do upload check for Candle receiver, making it no longer necessary to disable the MySensors add-on if you want to re-create it.
- Better handling of mobile devices (from 1.0.1)
- Unloads itself when not being viewed (but doesn't use the hide() function yet)
> Candle manager version 1.0.2

- addons/tellstick-adapter.json
- Support for Tellstick ZNet Lite V2
> Update Tellstick adapter to 0.2.0

- addons/power-settings.json
A pun on its ability to shutdown and restart your system, although more options were soon added. Making one add-on makes it easier to maintain.
It has no requirements.
FEATURES
- Shutdown your system
- Reboot your system
- Toggle fullscreen mode (pure javascript)
- Manually set the correct time
The last feature currently has an ability that warrent discussion. It can toggle whether the NTP daemon may use external servers to get the time. This is not a permanent setting (reboot and it's gone), it can only temporarily override this. It's fully optional.
I don't believe it hampers any of the other add-ons, since it's not like there will not be a time available. It also doesn't install anything new. It's just that by installing the add-on the user gains the ability to set the time manually. …
> First release of Power Settings

- addons/network-presence-detection-adapter.json
- To make the add-on more universal, this version moves use or `arping` behind try commands, and tries`ping` first.
- Re-adds a 5 second sleep between the continuous scans.
- Moves almost all print statements behind debug toggle.
- Tries to get the device's name from `nmblookup` where possible.
- Overall code improvement.
> Network presence detector 0.1.1

- addons/zigbee-adapter.json
Fixes mozilla-iot/zigbee-adapter#180
> Update Zigbee to 0.10.6.

- addons/myq-adapter.json
A runtime error is preventing the removal of a myQ device. upgrade myq-adapter to v0.1.2 to fix it.
> feat(myq): upgrades to v0.1.2 for `removeThing` runtime error fix

- addons/Candle-manager-addon.json
Small fix for users who enabled the tunneling feature / https. Before it tried to load the candle manager as http.
> Candle manager 1.0.5

- addons/mysensors-adapter.json
A bug was causing the recreation of devices from persistence to fail.
> MySensors 1.0.5 - fix handling of None values

- addons/Candle-manager-addon.json
- Can now handle empty #define strings
- Update of Arduino CLI to latest version
- Faster boot by moving init into a thread
- Fixed advanced options not showing up
- Fixed edge case where the list of sketches was multiplied
> Candle manager 1.0.7

- addons/sense-hat-adapter.json
Binary was build on rpi and uploaded to project releases.
Next version might use addon-builder.
Relate-to: https://github.com/rzr/sense-hat-webthing/issues/3
Change-Id: I3e022f80c9417df1d27dba78336b47012558d6ce
> sense-hat-adapter: Add version 0.0.3

- addons/sense-hat-adapter.json
URL is expected one once published by mozilla-iot
While checksum is the one from upstream's release file
but could differ if rebuilt using addon-builder.
Bug: https://github.com/rzr/sense-hat-webthing/issues/3
Relate-to: https://github.com/rzr/sense-hat-webthing/releases/tag/v0.0.5
Relate-to: https://github.com/rzr/sense-hat-webthing/releases/download/v0.0.5/sense-hat-adapter-0.0.5-linux-arm.tgz
> sense-hat: Update to 0.0.5 from 0.0.4

- addons/awox-mesh-light-adapter.json
Base version to validate builder
Relate-to: https://github.com/rzr/awox-mesh-light-webthing/releases/tag/v0.0.2
> awox-mesh-light-adapter: Add new adapter

- addons/matrix-adapter.json
Allows to post custom or predefined unencrypted messages to one Matrix room.
---
---
---
> Add Matrix Adapter

- addons/matrix-adapter.json
https://gitlab.com/webthings/matrix-adapter/-/blob/master/CHANGELOG.md#020-2020-06-26
* Posting now takes three properties: a message, a roomId and isNotice.
* Throw error when required config fields are missing.
* The room ID in the config became optional. The Notifier does not appear if no room ID got configured for it.
* A default roomID for messages can be specified.
* Added support for Notification Levels to the notifier.
---
---
> Matrix chat 0.2.1

- addons/internet-radio.json
- Volume is now set through ffplay instead of for the entire device. This makes it possible to set a relative volume. E.g. have the radio play at half the volume of Voco's output. The downside is that a volume change means ffplay is quickly restarted. The upside is that it can now offer volume control on USB audio cards that don't have a (simple) ALSA volume control option built in. This works around the inability to modify ALSA configuration settings at a more fundamental device level.
- Output device can now be set on the fly. This should also solve issues people were having with audio output, such as https://github.com/flatsiedatsie/internet-radio/issues/5
> Internet radio 1.1.0

- addons/voco.json
- a new way of selecting audio output via a thing property. This should help solve issues users were having with all kinds of (USB) device configurations.
- audio volume can now be relative to other volumes
- change in how listening can be disabled. Instead of disabling the hotword detector, it now simply blocks analysis. This is more robust.
- small improvements to heuristics in cases where the meaning is not fully understood.
- can now only toggle one property state at once when a generic "turn device X on" command is used. If the device has multiple on-off properties, it picks the first one. In a future version this could have a capability preference.
- Code cleanup, removes some things, like being able to upload a custom assistant. Since Snips no longer exists, this is moot.
> Voco 1.1.0

- addons/calendar.json
please integrate, I missed the most key part during the conversion to enum - it never recognises a holiday
> bugfix calendar - botched conversion to enum

- addons/square-theme.json
Adds log filtering feature, where uses can select which logs on the logs overview page they want to actually see.
This filtering list is toggled with a button in the top right corner of the screen. This bring up the question/suggestion: how about reserving that corner for add-on use?
> Square theme 1.0.0

- addons/p1-adapter
Almost all Dutch and Belgian homes now have a 'smart' energy meter that follow the P1 standard. Without support for this, most Dutchies smarh home enthousiasts won't switch to the WebThings Gateway.
Funnily enough I don't own a P1 meter myself. I used an Arduino to emulate it.
> Initial release of P1 adapter

- addons/highlights.json
HIghlights allows users to highligh any property on the things overview page. This is a workaround for https://github.com/mozilla-iot/gateway/issues/1826
> Initial release of Highlights

- addons/network-presence-detection-adapter.json
- shorter delay between continuous scans
- back up to 3 threads in the brute force scan
- Attempt to fix issue https://github.com/flatsiedatsie/webthings-network-presence-detection/issues/25
- small fix for issue https://github.com/flatsiedatsie/webthings-network-presence-detection/issues/30
> Network presence detection 1.1.0

- addons/calendar.json
- don't trigger error event on OK result
- correctly calculate reason, tag and source properties
- document new event
> calendar-v1.0.2

- addons/voco.json
- More rubust handling of satelite system, where sometimes a sytem (or the Voco addon) may not be up.
- Separation of hostname and site_id
- Small UI improvements (hostnames are exchanged and become visible)
- Option to do audio detection. Useful for home security, but also an interesting privacy case to try and handle.
- Option to say "hey Candle" as well
- Option to set initial system audio volume, to avoid issues of no audio output due to low volume.
> Voco 2.2.0

- addons/zigbee2mqtt-adapter.json
Mayor release.
- More flexible exposes scanning
- Wider implementation of webthings capabilities
- Extracts more properties, including whether a device can be updated.
- Ability to create additional properties based on partial or sub-optimal data (variable scaling and translation, e.g. color from hex to CIE pair)
- More options as per user request, such as disabling the built-in Zigbee2MQTT instance.
- UI for updating devices
- UI can show a map of the network
> Zigbee2MQTT version 0.4.0

- addons/zigbee2mqtt-adapter.json
- removes serialport from package.json
- adds vendor icons in device overview
> Zigbee2MQTT 0.4.6

- addons/zigbee2mqtt-adapter.json
- support for Zigbee2MQTT's `simulated_brightness` feature
- more robust handling of undefined config variables
- code simplication (e.g. color)
- fixes bug in color translation
- ability to choose prefered IKEA firmware update server
- different colors in map (in theory..)
> Zigbee2MQTT 0.4.7

- addons/zigbee2mqtt-adapter.json
An attempt to address issue https://github.com/kabbi/zigbee2mqtt-adapter/issues/32
Out of curiosity: could this situation happen?
- user installs addon
- Addon gains new feature which can be toggled in the addon settings
- user looks at the addon settings, and sees the toggle is `disabled`, which is their preference. They do not click `apply`.
- The addon doesn't get the actual boolean for the new feature, but gets an 'undefined'.
- In this situation the addon has to make a choice, and assumes the preference is `enabled`, which is the intended default.
- The user's perception and the addon's perception are now out of sync.
> Zigbee2MQTT 0.5.1

- addons/Candle-manager-addon.json
package script was deleting all Arduino binaries through `#find arduino-cli -mindepth 1 -maxdepth 1 \! -name "${ADDON_ARCH}" -exec rm -rf {} \;`
> Candle manager 1.1.8

- addons/voco.json
Removes Rapidfuzz dependency for fuzzy string matching
> Voco 2.5.6

- addons/voco.json
A bug in the previous code could cause a race condition where a lot of Voco processes would be started at the same time. A second typo caused protection against this to only be functional in debug mode.
> Voc 2.5.8 - fixes serious bug

- addons/zigbee2mqtt-adapter.json
Proper device ID's starting with z2m-
Recognises manually powering devices on and off (e.g. lightbulbs)
Data transmission privacy feature
> Zigbee2MQTT 0.6.0

- addons/psi-sg.json
The 2.5 micron Particulate Matter concentration (PM25), read hourly
in µg/m³ units, is a fast moving measurement of the most troublesome
pollutant in Singapore. The reading is interpreted with an additional
indicator.
This reading and indicator adds utility to the adapter, as the PSI is a
slow moving indicator averaged over 24 hours, so it often appears out of
line with reality.
> psi-sg v1.2.0 - Add the hourly PM25 concentration

- addons/date-time-adapter.json
Hi there, I wanted the feature in issue 16, and a few others, so I took it upon myself to update the date-time-adapter with fixes to the way @damooooooooooh was doing things (he had a bug where if the desired offset was after the sunset, it would never happen because the sunset time would be reset at sunset to the next day). I also added properties to tell you how long in minutes until the next sunset/sunrise, and how long it’s been since the last one. I also added a couple of properties that let you see the sun’s azimuth and elevation, so that you can detect things like certain angles when the sun shines in a window, or position/uncover solar panels at certain times, etc. My repo is a fork from @damooooooooooh’s last changes at https://github.com/wfahle/date-time-adapter, and I am …
> Changed date-time-adapter to my fork - wfahle

- addons/konnected-adapter.json
This adapter allows you to configure and add Konnected.io boards to WebThings gateway without having to use amazon cloud or konnected.io cloud. Konnected.io are boards that allow you to update or piggy-back on existing wired alarm systems for integration to home automation. Currently they work with most platforms; this work adds WebThings.io as one of those platforms.
> Initial stable release 0.0.3

- addons/square-theme.json
If a user has more than 20 devices, a quick filter search box will appear in the top-right corner of the things overview page. This allows them too quickly find the device by typing a few letters of the thing's title.
> Added things search box

- addons/matrix-adapter.json
* Changes to the new gateway 1.0.0 API, which has `.setTitle` and so on. So this no longer directly changes private properties of the Device and Outlet class.
* A small bugfix to predefined messages always getting posted in the default room.
https://gitlab.com/webthings/matrix-adapter/-/tags/v0.4.1
For anyone interested, send issue reports and pull requests this way:
https://gitlab.com/webthings/matrix-adapter
> Add matrix-adapter 0.4.1

- addons/irusb-adapter.json
Primarily fixes actions not doing anything due to testing against upstream gateway instead of release.
> irusb-adapter v1.0.1

- addons/date-time-adapter.json
Got the 3.7 python build to work by using existing wheels in the build rather than request --no-binary in the package.sh. This might work for others with build problems.
> Fixed issue with 3.7 build

- addons/avocet.json
Lightweight, local and polyglot voice assistant.
Built around PicoVoice and the Respeaker 2-MIC hat.
See: [Avocet repo](https://github.com/Bleznudd/avocet)
> New addon: avocet

- addons/zigbee-adapter.json
Technically I should probably be setting the maximum gateway version for the zigbee-adapter 0.21.1 packages to 1.1.0 for the darwin architecture, but if I do that the CI checks fail because the actual package manifests don't specify that.
We should probably have a way to do that without re-releasing a previous release...
> Update zigbee-adapter to 0.22.0 on everything except darwin
